version: '2'

services:
  app:
    image: p0bailey/docker-flask
    container_name: flask
    volumes:
    - "./app:/var/www/app"
    ports:
      - "8080:80"
    links:
      - db

  db:
    image: mariadb
    container_name: flask-db
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
